/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.RicevoColoreRegole.play1;
import static GUI.SceltaRegole.play1;
import Gestione.GestioneRegole;
import Gestione.Regole;
import scacchip2p.Peer;

/**
 *
 * @author Giorgia
 */
public class partitaPersonalizzata extends javax.swing.JFrame {

    static Peer play1;

    /**
     * Creates new form partitaPersonalizzata
     */
    public partitaPersonalizzata(Peer play1) {
        initComponents();
        this.play1 = play1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aiutiGroup = new javax.swing.ButtonGroup();
        tempoGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aiutiY = new javax.swing.JRadioButton();
        aiutiN = new javax.swing.JRadioButton();
        tempoY = new javax.swing.JRadioButton();
        tempoN = new javax.swing.JRadioButton();
        comboTipo = new javax.swing.JComboBox<>();
        btnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personalizzata");

        jLabel1.setText("Aiuti:");

        jLabel2.setText("Tempo:");

        jLabel3.setText("Tipo di scacchi:");

        aiutiGroup.add(aiutiY);
        aiutiY.setText("Sì");

        aiutiGroup.add(aiutiN);
        aiutiN.setText("No");

        tempoGroup.add(tempoY);
        tempoY.setText("Sì");

        tempoGroup.add(tempoN);
        tempoN.setText("No");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard" }));

        btnConferma.setText("Conferma");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(aiutiN)
                    .addComponent(aiutiY))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tempoY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tempoN)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnConferma)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aiutiY)
                    .addComponent(tempoY)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aiutiN)
                    .addComponent(tempoN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnConferma)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        // TODO add your handling code here:
        Regole r = null;
        if (aiutiY.isSelected() && tempoY.isSelected()) {
            r = new Regole(true, true, 100, comboTipo.getItemAt(comboTipo.getSelectedIndex()).toString());
        } else if (aiutiY.isSelected() && tempoN.isSelected()) {
            r = new Regole(true, false, 100, comboTipo.getItemAt(comboTipo.getSelectedIndex()).toString());
        } else if (aiutiN.isSelected() && tempoY.isSelected()) {
            r = new Regole(false, true, 100, comboTipo.getItemAt(comboTipo.getSelectedIndex()).toString());
        } else if (aiutiN.isSelected() && tempoN.isSelected()) {
            r = new Regole(false, false, 100, comboTipo.getItemAt(comboTipo.getSelectedIndex()).toString());
        }

        play1.getDati().setRegole(r);
        GestioneRegole gr = new GestioneRegole(play1);

        String messagioDaInviare = gr.personalizzata(r.isTempo(), r.isAiuti(), r.getTipoScacchi());
        play1.getClient().send(messagioDaInviare);

        String messaggio = play1.getServer().ascolta();

        String campi[] = messaggio.split(";");

        if (campi[0].equals("y")) {
            this.setVisible(false);
            this.dispose();//libera memoria dalle cose create

            Board board = new Board(play1);
            board.setVisible(true);
        } else {
            this.setVisible(false);
            this.dispose();//libera memoria dalle cose create

            play1.chiudiTutto();

            PaginaIniziale iniziale = new PaginaIniziale();
            iniziale.setVisible(true);
        }
    }//GEN-LAST:event_btnConfermaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partitaPersonalizzata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partitaPersonalizzata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partitaPersonalizzata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partitaPersonalizzata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partitaPersonalizzata(play1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup aiutiGroup;
    private javax.swing.JRadioButton aiutiN;
    private javax.swing.JRadioButton aiutiY;
    private javax.swing.JButton btnConferma;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.ButtonGroup tempoGroup;
    private javax.swing.JRadioButton tempoN;
    private javax.swing.JRadioButton tempoY;
    // End of variables declaration//GEN-END:variables
}
