/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Pezzi.Alfiere;
import Pezzi.Cavallo;
import Pezzi.Punto;
import Pezzi.Regina;
import Pezzi.Torre;
import javax.swing.JDialog;

/**
 *
 * @author Alber
 */
public class Prova extends javax.swing.JPanel {

    public Punto c;
    JDialog cd;

    /**
     * Creates new form Prova
     */
    public Prova(JDialog cd) {
        initComponents();
        this.cd = cd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCavallo = new javax.swing.JButton();
        btnTorre = new javax.swing.JButton();
        btnRegina = new javax.swing.JButton();
        btnAlfiere = new javax.swing.JButton();

        btnCavallo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pezzi/assets/cavallo-b.png"))); // NOI18N
        btnCavallo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCavalloActionPerformed(evt);
            }
        });

        btnTorre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pezzi/assets/torre-b.png"))); // NOI18N
        btnTorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorreActionPerformed(evt);
            }
        });

        btnRegina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pezzi/assets/regina-b.png"))); // NOI18N
        btnRegina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReginaActionPerformed(evt);
            }
        });

        btnAlfiere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pezzi/assets/alfiere-b.png"))); // NOI18N
        btnAlfiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlfiereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCavallo)
                        .addGap(114, 114, 114)
                        .addComponent(btnTorre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlfiere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegina)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCavallo)
                    .addComponent(btnTorre))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlfiere)
                    .addComponent(btnRegina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCavalloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCavalloActionPerformed
        // TODO add your handling code here:
        c = new Punto(0, 0, new Cavallo("N", false));
        cd.setModal(false);
        cd.setFocusable(false);
        cd.dispose();

    }//GEN-LAST:event_btnCavalloActionPerformed

    private void btnTorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorreActionPerformed
        // TODO add your handling code here:
        c = new Punto(0, 0, new Torre("R", false));
        cd.setModal(false);
        cd.setFocusable(false);
        cd.dispose();
    }//GEN-LAST:event_btnTorreActionPerformed

    private void btnReginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReginaActionPerformed
        // TODO add your handling code here:
        c = new Punto(0, 0, new Regina("Q", false));
        cd.setModal(false);
        cd.dispose();

    }//GEN-LAST:event_btnReginaActionPerformed

    private void btnAlfiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlfiereActionPerformed
        // TODO add your handling code here:
        c = new Punto(0, 0, new Alfiere("B", false));
        cd.setModal(false);
        cd.dispose();
    }//GEN-LAST:event_btnAlfiereActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlfiere;
    private javax.swing.JButton btnCavallo;
    private javax.swing.JButton btnRegina;
    private javax.swing.JButton btnTorre;
    // End of variables declaration//GEN-END:variables
}
