/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.RicevoColoreRegole.play1;
import Gestione.GestioneRegole;
import Gestione.Regole;
import scacchip2p.DatiCondivisi;
import scacchip2p.Peer;

/**
 *
 * @author Giorgia
 */
public class SceltaRegole extends javax.swing.JFrame {

    int regole = 0; //amichevole=0, competitiva=1, personalizzata=2
    static Peer play1;
    Regole r;

    /**
     * Creates new form SceltaRegole
     */
    public SceltaRegole(Peer play1) {
        initComponents();
        this.play1 = play1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAmichevole = new javax.swing.JButton();
        btnCompetitiva = new javax.swing.JButton();
        btnPersonalizzata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scelta regole");

        btnAmichevole.setText("Amichevole ");
        btnAmichevole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmichevoleActionPerformed(evt);
            }
        });

        btnCompetitiva.setText("Competitiva");
        btnCompetitiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompetitivaActionPerformed(evt);
            }
        });

        btnPersonalizzata.setText("Personalizzata");
        btnPersonalizzata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalizzataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAmichevole, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnCompetitiva)
                .addGap(29, 29, 29)
                .addComponent(btnPersonalizzata)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAmichevole, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompetitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersonalizzata, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalizzataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalizzataActionPerformed
        // TODO add your handling code here:
        regole = 2;

//        GestioneRegole gr = new GestioneRegole(play1);
        this.setVisible(false);
        this.dispose();//libera memoria dalle cose create

        partitaPersonalizzata p = new partitaPersonalizzata(play1);
        p.setVisible(true);

    }//GEN-LAST:event_btnPersonalizzataActionPerformed

    private void btnAmichevoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmichevoleActionPerformed
        // TODO add your handling code here:
        regole = 0;

        r = new Regole(true, 0, 100, "Standard");

        play1.getDati().setRegole(r);

        GestioneRegole gr = new GestioneRegole(play1);

        String messagioDaInviare = gr.amichevole();
        play1.getClient().send(messagioDaInviare);

        String messaggio = play1.getServer().ascolta();

        String campi[] = messaggio.split(";");

        if (campi[0].equals("y")) {
            this.setVisible(false);
            this.dispose();//libera memoria dalle cose create

            Board board = new Board(play1);
            board.setVisible(true);
        } else {
            this.setVisible(false);
            this.dispose();//libera memoria dalle cose create

            play1.chiudiTutto();
            PaginaIniziale iniziale = new PaginaIniziale();
            iniziale.setVisible(true);
        }


    }//GEN-LAST:event_btnAmichevoleActionPerformed

    private void btnCompetitivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompetitivaActionPerformed
        // TODO add your handling code here:
        regole = 1;

        r = new Regole(false, 10, 100, "Standard");

        play1.getDati().setRegole(r);

        GestioneRegole gr = new GestioneRegole(play1);

        String messagioDaInviare = gr.competitiva();
        play1.getClient().send(messagioDaInviare);

        String messaggio = play1.getServer().ascolta();

        String campi[] = messaggio.split(";");

        if (campi[0].equals("y")) {
            this.setVisible(false);
            this.dispose();//libera memoria dalle cose create

            Board board = new Board(play1);
            board.setVisible(true);
        } else {
            this.setVisible(false);
            this.dispose();//libera memoria dalle cose create

            play1.chiudiTutto();
            PaginaIniziale iniziale = new PaginaIniziale();
            iniziale.setVisible(true);
        }
    }//GEN-LAST:event_btnCompetitivaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SceltaRegole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SceltaRegole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SceltaRegole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SceltaRegole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SceltaRegole(play1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmichevole;
    private javax.swing.JButton btnCompetitiva;
    private javax.swing.JButton btnPersonalizzata;
    // End of variables declaration//GEN-END:variables
}
